on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

name: run tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [ '1.19', '1.18' ]
        platform: [ 'ubuntu-latest' ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          stable: ${{ !contains(matrix.go-version, 'beta') }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -v ./...
